In [11]:
# Dependencies
import pandas as pd
import numpy as np

In [12]:
# Store filepaths in dataframes
Airbnb_df = "data/AirBNB.csv"
Airbnb_df = pd.read_csv(Airbnb_df)
Airbnb_df.head()

/Users/kusry/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,scrape_id_YYYYMM,last_scraped,name,host_id,host_since,street,neighbourhood,zipcode,latitude,...,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,last_review_YYYYMM,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,295240,201505,5/4/2015,Luxury Apartment Oasis w/ Hot Tub,1525192,12/21/2011,"Ord St, San Francisco, CA 94114, United States",The Castro,94114,37.762674,...,6.0,11.0,215.0,23,2/11/2012,4/1/2015,201504,NaN,NaN,NaN
1,4882829,201505,5/4/2015,Private room in Inner Richmond,25118670,12/23/2014,"4th Avenue, San Francisco, CA 94118, United St...",Richmond District,94118,37.778993,...,19.0,19.0,111.0,1,4/22/2015,4/22/2015,201504,NaN,NaN,NaN
2,4850420,201505,5/4/2015,Edge of SOMA + the Mission,1358761,11/1/2011,"12the ave. and Folsom St, San Francisco, CA 94...",NaN,94103,37.771447,...,0.0,0.0,111.0,0,NaN,NaN,190001,NaN,NaN,NaN
3,1278848,201505,5/4/2015,Sunny Nob Hill 1 br (entire apt),6959333,6/17/2013,"Sacramento Street, San Francisco, CA 94109, Un...",Nob Hill,94109,37.790745,...,1.0,5.0,129.0,11,7/18/2013,2/15/2015,201502,NaN,NaN,NaN
4,5068275,201505,5/4/2015,Huge & Sunny 1BR Loft,350767,1/17/2011,"Minnesota Street, San Francisco, CA 94107, Uni...",Dogpatch,94107,37.759449,...,0.0,0.0,9.0,5,2/7/2015,3/29/2015,201503,NaN,NaN,NaN

In [13]:
len(Airbnb_df)

456771

In [14]:
#Drop duplicate scrapes from 1/4/20, 11/8/17, 12/7/17 & 1/17/18
Airbnb_clean_df_r01_04_2020 = Airbnb_df[Airbnb_df.last_scraped != "1/4/2020"]
Airbnb_clean_df_r11_08_2017 = Airbnb_clean_df_r01_04_2020[Airbnb_clean_df_r01_04_2020.last_scraped != "11/8/2017"]
Airbnb_clean_df_r12_07_2017 = Airbnb_clean_df_r11_08_2017[Airbnb_clean_df_r11_08_2017.last_scraped != "12/7/2017"]
Airbnb_clean_df = Airbnb_clean_df_r12_07_2017[Airbnb_clean_df_r12_07_2017.last_scraped != "1/17/2018"]

#Pull just the columns you need
Airbnb_clean_df = Airbnb_clean_df[['id','last_scraped','neighbourhood','price','room_type','zipcode','latitude','longitude']]

len(Airbnb_clean_df)

429422

In [15]:
#Convert last_scaped to date format
Airbnb_clean_df['last_scraped'] = pd.to_datetime(Airbnb_clean_df['last_scraped'], errors='coerce')

#Split the data by month & year and place into new columns
Airbnb_clean_df['month'] = Airbnb_clean_df['last_scraped'].dt.month
Airbnb_clean_df['year'] = Airbnb_clean_df['last_scraped'].dt.year

# Drop years you do not need (anything prior to 2017)
Airbnb_clean_df_2015 = Airbnb_clean_df[Airbnb_clean_df.year != 2015]
Airbnb_clean_df = Airbnb_clean_df_2015[Airbnb_clean_df_2015.year != 2016]
Airbnb_clean_df

,id,last_scraped,neighbourhood,price,room_type,zipcode,latitude,longitude,month,year
111400,8388658,2017-01-01,Sea Cliff,895,Entire home/apt,94121,37.787664,-122.489152,1,2017
111401,1427660,2017-01-01,Richmond District,150,Entire home/apt,94121,37.775236,-122.509137,1,2017
111402,15664146,2017-01-01,Richmond District,295,Entire home/apt,94121,37.784365,-122.489515,1,2017
111403,15285867,2017-01-01,NaN,98,Private room,94121,37.786343,-122.489570,1,2017
111404,16362304,2017-01-01,Richmond District,85,Private room,94121,37.779841,-122.505483,1,2017
...,...,...,...,...,...,...,...,...,...,...
456766,44088881,2020-07-07,SoMa,225,Entire home/apt,94114,37.763350,-122.439663,7,2020
456767,44097782,2020-07-07,Downtown,67,Private room,94109,37.787686,-122.416442,7,2020
456768,44098996,2020-07-07,Alamo Square,140,Entire home/apt,94117,37.777347,-122.434137,7,2020
456769,44099008,2020-07-07,Mission Bay,166,Entire home/apt,94158,37.772020,-122.390416,7,2020
456770,44102103,2020-07-07,SoMa,111,Entire home/apt,94110,37.774003,-122.418490,7,2020

In [16]:
# Convert month & year integers to strings so you can combine
Airbnb_clean_df['year'] = Airbnb_clean_df['year'].astype(str)
Airbnb_clean_df['month'] = Airbnb_clean_df['month'].astype(str)

# Combine month & year in one column and add a zero
Airbnb_clean_df['month_scraped'] = Airbnb_clean_df['year'].str.cat(Airbnb_clean_df['month'],sep="-0")

# Now remove the zero from double digit months
Airbnb_clean_df['month_scraped'] = Airbnb_clean_df['month_scraped'].replace({
    "2020-012":"2020-12","2019-012":"2019-12","2018-012":"2018-12","2017-012":"2017-12",
    "2020-011":"2020-11","2019-011":"2019-11","2018-011":"2018-11","2017-011":"2017-11",
    "2020-010":"2020-10","2019-010":"2019-10","2018-010":"2018-10","2017-010":"2017-10"
})
Airbnb_clean_df

/Users/kusry/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/kusry/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/kusry/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/kusry/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,id,last_scraped,neighbourhood,price,room_type,zipcode,latitude,longitude,month,year,month_scraped
111400,8388658,2017-01-01,Sea Cliff,895,Entire home/apt,94121,37.787664,-122.489152,1,2017,2017-01
111401,1427660,2017-01-01,Richmond District,150,Entire home/apt,94121,37.775236,-122.509137,1,2017,2017-01
111402,15664146,2017-01-01,Richmond District,295,Entire home/apt,94121,37.784365,-122.489515,1,2017,2017-01
111403,15285867,2017-01-01,NaN,98,Private room,94121,37.786343,-122.489570,1,2017,2017-01
111404,16362304,2017-01-01,Richmond District,85,Private room,94121,37.779841,-122.505483,1,2017,2017-01
...,...,...,...,...,...,...,...,...,...,...,...
456766,44088881,2020-07-07,SoMa,225,Entire home/apt,94114,37.763350,-122.439663,7,2020,2020-07
456767,44097782,2020-07-07,Downtown,67,Private room,94109,37.787686,-122.416442,7,2020,2020-07
456768,44098996,2020-07-07,Alamo Square,140,Entire home/apt,94117,37.777347,-122.434137,7,2020,2020-07
456769,44099008,2020-07-07,Mission Bay,166,Entire home/apt,94158,37.772020,-122.390416,7,2020,2020-07
456770,44102103,2020-07-07,SoMa,111,Entire home/apt,94110,37.774003,-122.418490,7,2020,2020-07

In [17]:
len(Airbnb_clean_df)

318022

In [19]:
# Sort by price to identify any abnormalities
Airbnb_clean_df_sorted = Airbnb_clean_df.sort_values(by=['price'], ascending=False)
Airbnb_clean_df_sorted[:20]

,id,last_scraped,neighbourhood,price,room_type,zipcode,latitude,longitude,month,year,month_scraped
160898,18448377,2017-06-02,SoMa,30000,Entire home/apt,94103,37.779502,-122.403861,6,2017,2017-06
151658,18448377,2017-05-03,SoMa,30000,Entire home/apt,94103,37.779502,-122.403861,5,2017,2017-05
382127,39459574,2019-11-01,Richmond District,25000,Entire home/apt,94121,37.772850,-122.497510,11,2019,2019-11
399105,40207461,2020-01-02,Financial District,25000,Entire home/apt,94111,37.792520,-122.397730,1,2020,2020-01
449240,43688753,2020-06-08,Telegraph Hill,25000,Entire home/apt,94133,37.799760,-122.403590,6,2020,2020-06
116988,10724176,2017-01-01,South Beach,10000,Entire home/apt,94107,37.780338,-122.391903,1,2017,2017-01
439674,36185495,2020-05-06,Nob Hill,10000,Hotel room,94109,37.793410,-122.420510,5,2020,2020-05
455198,37674309,2020-07-07,Downtown,10000,Private room,94102,37.786370,-122.407850,7,2020,2020-07
433868,1059961,2020-05-06,SoMa,10000,Shared room,94103,37.779810,-122.410220,5,2020,2020-05
250229,19905527,2018-04-06,Sea Cliff,10000,Entire home/apt,94121,37.786235,-122.493417,4,2018,2018-04
414924,36147990,2020-02-12,SoMa,10000,Private room,94103,37.779520,-122.410770,2,2020,2020-02
162484,8614819,2017-06-02,Nob Hill,10000,Entire home/apt,94108,37.791712,-122.408741,6,2017,2017-06
455197,37674141,2020-07-07,Downtown,10000,Private room,94102,37.786790,-122.408010,7,2020,2020-07
414925,36148137,2020-02-12,SoMa,10000,Private room,94103,37.772850,-122.409480,2,2020,2020-02
414926,36148199,2020-02-12,SoMa,10000,Private room,94103,37.772000,-122.411030,2,2020,2020-02
439668,36185208,2020-05-06,Downtown,10000,Hotel room,94109,37.788170,-122.417380,5,2020,2020-05
439673,36185434,2020-05-06,Nob Hill,10000,Hotel room,94109,37.793340,-122.420460,5,2020,2020-05
431596,36003207,2020-04-08,SoMa,10000,Private room,94103,37.772640,-122.409910,4,2020,2020-04
431595,36003038,2020-04-08,SoMa,10000,Private room,94103,37.778530,-122.410490,4,2020,2020-04
414927,36148437,2020-02-12,SoMa,10000,Private room,94103,37.772190,-122.409110,2,2020,2020-02

In [20]:
# Drop junk data listing
Airbnb_clean_df = Airbnb_clean_df[Airbnb_clean_df.id != 18448377]
len(Airbnb_clean_df)

318020

In [21]:
# Export to CSV
Airbnb_clean_df.to_csv('data/AirbnbCleaned.csv', encoding='utf-8', index=False)